<?php
/**
 * ======================================================================
 * LICENSE: This file is subject to the terms and conditions defined in *
 * file 'license.txt', which is part of this source code package.       *
 * ======================================================================
 */
$factory = Router::get('Factory');
$ui = Router::call('Settings.ui');
$preference = Router::call('Settings.preference');
?>
<div class="wrap" id="ahm_content">
    <div class="ahm-header">
        <span class="ahm-title"><?php echo $factory->lang('WP Error Fix'); ?></span>
        <span class="ahm-subtitle"><?php echo $factory->lang('Keep Your Website Error Free'); ?></span>
    </div>
    <div class="postbox-container" style="width:75%; position: relative;">
        <div class="metabox-holder">
            <div id="metabox-main" class="postbox">
                <div class="handlediv" title="<?php echo $factory->lang('Click to toggle'); ?>"><br /></div>
                <h3 class="hndle"><span></span></h3>
                <div class="inside" id="view_list">
                    <div class="graph hide">
                        <div class="graph-list">
                            <a href="#" class="graph-type graph-line"><span><?php echo $factory->lang('Error Counter'); ?></span></a>
                            <a href="#" class="graph-type graph-pie"><span><?php echo $factory->lang('Impact Counter'); ?></span></a>
                        </div>
                        <div class="graph-container">
                            <div id="graph-lines"></div>
                            <div id="graph-pie"></div>
                        </div>
                        <div class="graph-explain hide" id="explain_line">
                            <?php echo sprintf($factory->lang('The graph shows the total number of Errors, Warnings and Notices detected by WP Error Fix for last %s days, grouped by day they appeared.'), AHM_ERROR_DAYCOUNT); ?>
                        </div>
                        <div class="graph-explain hide" id="explain_pie">
                            <?php echo $factory->lang('The pie graph indicates the negative impact each plugin or theme has on your WordPress installation. As bigger pie cut, as higher negative impact.'); ?>
                        </div>
                        <div class="empty-error-log">
                            <span></span>
                        </div>
                    </div>
                    <div class="list hide">
                        <table class="display" id="list">
                            <thead>
                                <tr>
                                    <th style="width:70%;"><?php echo $factory->lang('Message'); ?></th>
                                    <th><?php echo $factory->lang('Last Time (Occured)'); ?></th>
                                    <th style="width: 10%;"><?php echo $factory->lang('Status'); ?></th>
                                    <th><?php echo $factory->lang('Type'); ?></th>
                                    <th><?php echo $factory->lang('Module'); ?></th>
                                    <th><?php echo $factory->lang('Solution'); ?></th>
                                    <th><?php echo $factory->lang('Reason'); ?></th>
                                </tr>
                            </thead>
                            <tbody/>
                        </table>
                    </div>
                    <div class="about ahm-content hide">
                        <b>WP Error Fix</b> is a simple plugin designed to keep your website error free. It
                        catches all errors triggered by plugins, themes or WordPress and display in easy-to-understand format.</br>
                        <br/>
                        <b>How to suppress all errors?</b><br/>
                        There is a way to suppress any error on your website and at the same time track its occurrence.<br/>
                        Find the <b>wp-config.php</b> file (it is usually in the same folder as <b>index.php</b>).
                        Open it and make sure that <span style='color:#0000e6;'>WP_DEBUG</span>
                        is set to "<span style='color:#800000; font-weight:bold;'>false</span>"
                        (in case you want to use the debug mode you can leave it "<span style='color:#800000;font-weight:bold;'>true</span>").
                        Now you need to bootstrap the <b>WP Error Fix</b>
                        with next line of code (put it right after <span style='color:#0000e6;'>WP_DEBUG</span> definition):
                        <div class="code-container">
                            <span style='color:#800000; background:#ffffe8; font-weight:bold;'>require_once</span>
                            <span style='color:#808030; background:#ffffe8; '>(</span>
                            <span style='color:#0000e6; background:#ffffe8; '>
                                '<?php echo realpath(Router::call('Factory.basePluginDir') . '/bootstrap.php'); ?>'
                            </span>
                            <span style='color:#808030; background:#ffffe8; '>)</span>
                            <span style='color:#800080; background:#ffffe8; '>;</span>
                            <span style='color:#000000; background:#ffffe8; '></span>
                        </div>
                        <br/>
                        <b>Would you like to know more?</b><br/>
                        Fill free to send us an email at <a href="mailto:support@phpsnapshot.com">support@phpsnapshot.com</a>.
                        </p>
                    </div>
                    <div class="register ahm-content hide">
                        <div class="progress progress-loader">Registration...</div>
                        <p>WP Error Fix is registering your WordPress installation. Please wait just a second. &nbsp;<a href="#" id="registration_more">Read more...</a></p>
                        <p class="hide">
                            Your interest in WP Error Fix is very important for us.
                            This registration process will notify our system about your WordPress installation.
                            As a response, unique key will be received to identify your system.
                        </p>
                    </div>
                    <div class="analyze ahm-content hide">
                        <div class="progress progress-loader">Analyzing...</div>
                        <p>WP Error Fix is analyzing system error logs. Please wait a little. In case of big logs, this process may take a minute.</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="ahm-javascript-error">
            <span><?php echo $factory->lang('Unexpected Application Failure'); ?></span>
        </div>
        <div class="ahm-dialog" id="purchase_support">
            <div class="ahm-dialog-header">
                <span class="ahm-dialog-title">
                    <?php echo $factory->lang('Request Support'); ?>
                </span>
            </div>
            <div class="ahm-dialog-content">
                <p class="balance-additional-notice">
                    <b>Keep your website error free with us</b>. Request our support today and we will fix
                    all your issues tomorrow! We charge $75 per hour but you get <b>first 2 hours for 
                    the price of one hour</b>.<br/><br/>
                    Please notice that we might need FTP or SFTP access to your web to physically
                    modify file. This is necessary procedure to resolve errors in your system.<br/><br/>
                    For security reason, we do not store any credentials that we receive from you.
                </p>
            </div>
            <div class="ahm-dialog-footer">
                <div class="paypal-sign"></div>
                <a href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=XVVCVWYPKR3UQ&custom=<?php echo Router::call('Settings.account'); ?>" class="button button-primary button-large" target="_blank">Get Support Today</a>
                <a href="#" class="button button-primary button-large" id="support_cancel">Cancel</a>
            </div>
        </div>
        <div class="ahm-dialog" id="preferences_form">
            <div class="ahm-dialog-header">
                <span class="ahm-dialog-title">
                    <?php echo $factory->lang('Your Preferences'); ?>
                </span>
            </div>
            <div class="ahm-dialog-content">
                <table class="preferences-list">
                    <tbody>
                        <tr>
                            <td>
                                <input type="checkbox" id="preference_notify_error" value="on" <?php echo (isset($preference['notify']['error']) ? 'checked="checked"' : ''); ?> />
                            </td>
                            <td>
                                <?php echo $factory->lang('Notify me when Error(s) occured.'); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <input type="checkbox" id="preference_notify_solution" value="on" <?php echo (isset($preference['notify']['solution']) ? 'checked="checked"' : ''); ?> />
                            </td>
                            <td>
                                <?php echo $factory->lang('Notify me when Solution is available.'); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Email:
                            </td>
                            <td>
                                <input type="text" class="ahm-input" id="preference_email" value="<?php echo (isset($preference['email']) ? $preference['email'] : ''); ?>" />
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="ahm-dialog-footer">
                <a href="#" class="button button-primary button-large" id="update_preferences">Update</a>
                <a href="#" class="button button-primary button-large" id="cancel_preferences">Cancel</a>
            </div>
        </div>
    </div>
    <div class="sidebox-container">
        <div class="metabox-holder">
            <div id="submitdiv" class="postbox">
                <div class="handlediv" title="<?php echo $factory->lang('Click to toggle'); ?>"><br /></div>
                <h3 class="hndle"><span><?php echo $factory->lang('Control panel'); ?></span></h3>
                <div class="inside">
                    <div class="sidebar-content">
                        <div id="current_view">
                            <div class="ahm-menu graph" view="graph" title="<?php echo $factory->lang('Statistics & Graphs'); ?>"></div>
                            <div class="ahm-menu list" view="list" title="<?php echo $factory->lang('Error List'); ?>"></div>
                            <div class="ahm-menu support" title="<?php echo $factory->lang('Support'); ?>" id="support"></div>
                        </div>
                        <div class="minor-table">
                            <?php if (!isset($ui['registered']) || !$ui['registered']) { ?>
                                <a href="#" class="minor-table-action minor-table-action-register" id="register" title="Register your system"></a>
                            <?php } ?>
                            <a href="#" class="minor-table-action minor-table-action-trash" title="Clear All Reports" id="delete"></a>
                            <a href="http://www.linkedin.com/in/vasylmartyniuk" target="_blank" class="minor-table-action minor-table-action-linkedin" title="About Author"></a>
                            <a href="https://twitter.com/wpaam" target="_blank" class="minor-table-action minor-table-action-twitter" title="Follow @wpaam"></a>
                            <a href="#" class="minor-table-action minor-table-action-info" title="Info" id="info"></a>
                            <a href="#" class="minor-table-action minor-table-action-settings" id="open_preferences" title="Settings"></a>
                            <a href="http://wordpress.org/support/view/plugin-reviews/wp-error-fix" target="_blank" class="minor-table-action minor-table-action-star" title="Reviews"></a>
                        </div>
                    </div>
                </div>
                <div class="control-message hide" id="clear">
                    <p class="message-holder"><b>Are you really want to clean all error logs?</b></p>
                    <a href="#" class="button button-primary button-large" id="clear_yes">Yes</a>
                    <a href="#" class="button button-primary button-large" id="clear_no">No</a>
                </div>
                <div class="control-message hide" id="reload">
                    <p class="message-holder"><b>Operation is completed. Please reload the page.</b></p>
                    <a href="#" class="button button-primary button-large" id="reload_page">Reload</a>
                </div>
            </div>
        </div>
    </div>
</div>